const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";
const NEW_ATTACHMENTS = "NEW_ATTACHMENTS";
const NEW_MESSAGES = "NEW_MESSAGES";
const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGES_ALERT = "NEW_MESSAGES_ALERT";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";

const ONLINE_USERS = "ONLINE_USERS";

export {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENTS,
  NEW_MESSAGES,
  NEW_REQUEST,
  NEW_MESSAGES_ALERT,
  START_TYPING,
  STOP_TYPING,
  CHAT_JOINED,
  CHAT_LEAVED,
  ONLINE_USERS,
};
